### ISSUE TITLE
Error when npm installing 1.7.0

### ISSUE THREAD

**Issue by esride-nik** [sanack/node-jq#163] opened 2019-04-18 14:00 UTC
Hey guys, it seems that there's an issue with the latest version. We tried on 3 different machines, all current NPM versions, in repos where it used to work before and in empty folders, and it always says:

```
npm ERR! path <DEV_PATH>\node_modules\node-jq\bin\jq
npm ERR! code ENOENT
npm ERR! errno -4058
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '<DEV_PATH>\node_modules\node-jq\bin\jq'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

Installing an older version works: `npm install node-jq@1.5.0`

**Comment by davesnx** [comment] 2019-04-18 16:16
Thanks for reporting, I will take a look.

**Comment by davesnx** [comment] 2019-04-18 17:07
I was taking a look at the issue happened https://ci.appveyor.com/project/sanack/node-jq/builds/23923362/job/299dacxnfpog3a78 and seems that it's a node error happening when you try to change the permissions to downloaded jq. 

The issue posted on nodejs is here https://github.com/nodejs/node/issues/20498

**Comment by davesnx** [comment] 2019-04-18 19:51
Could you try with `node-jq@1.7.1`?

**Comment by jakobwgnr** [comment] 2019-04-19 08:43
hello! Getting the same error when trying to install 1.7.1

FYI don't know if relevant - I'm working on a windows machine

**Comment by sirpy** [comment] 2019-04-23 15:26
1.6.0 works on macosx 1.7+ doesnt.

**Comment by imoark** [comment] 2019-05-07 01:55
I can install on WSL for node-jq@1.5.0
But I can't run it over the script, saying `sh: 1: ./node_modules/node-jq/bin/jq: not found`
Details here https://github.com/sanack/node-jq/pull/143#issuecomment-489872126

**Comment by davesnx** [comment] 2019-05-07 07:53
> 1.6.0 works on macosx 1.7+ doesnt.

Which error are you facing?

**Comment by davesnx** [comment] 2019-05-09 15:44
I tried personally, and fails only with npm (my version is 6.4.1).

Could you share your npm's version @sirpy @jakobwgnr

**Comment by davesnx** [comment] 2019-05-09 16:09
It's fixed in `@1.8.1`

The key `bin` inside the packagejson makes npm (and not yarn) to change the permisions just before the install (before the install script too), this is why it was failing. I lost my head a little bit here... 

Sorry for the apologies folks!

**Closed by davesnx** 2019-05-09 16:09 UTC

**Comment by kseniamukhortova** [comment] 2021-05-27 15:50
Hi! I'm using version 1.12.0 and the issue is reappearing on unix. Bin folder is missing in node_modules/node-jq after yarn install

**Comment by davesnx** [comment] 2021-05-27 15:55
Can you make a reproduction example that I can look into?

**Comment by kseniamukhortova** [comment] 2021-05-28 06:19
It turned out that bin folder is missing if I call `yarn install --ignore-scripts` - I needed this flag for own purposes but wasn't aware it will affect jq binary installation

**Comment by kseniamukhortova** [comment] 2021-05-28 06:55
It is also very unfortunate, that after it is installed without bin folder, further calls to 'yarn install' (without --ignore-scripts flag) don't end up in installing bin, as it supposes everything is installed already.

**Comment by davesnx** [comment] 2021-05-28 08:21
Right, `--ignore-scripts` will not run the npm post-install scripts, which in node-jq case, installs the jq binary from github.

I'm not sure if I understand this part:
> It is also very unfortunate, that after it is installed without bin folder, further calls to 'yarn install' (without --ignore-scripts flag) don't end up in installing bin, as it supposes everything is installed already

If you want to keep the `--ignore-scripts` in your installation, I think there are 2 options available:

1. Run `npm install --ignore-scripts` (and keep node-jq outside of the dependencies) and run `npm install node-jq` separately.
2. Keep the `npm install --ignore-scripts`, but make sure you have jq installed in your system and available in $PATH.

Hope this helps

**Comment by kseniamukhortova** [comment] 2021-05-28 08:30
Thanks, will give it a try! Probably, it would be good to note in the documentation somewhere that node-jq requires postinstall scripts to be run.

**Comment by davesnx** [comment] 2021-05-28 08:37
There's a paragraph explaining that:

> By default, `node-jq` downloads jq on the installation process (when you run `npm install node-jq`). Downloads the binaries according to your SO.

Will improve it, Thanks

**Comment by kseniamukhortova** [comment] 2021-05-28 08:58
> Keep the npm install --ignore-scripts, but make sure you have jq installed in your system and available in $PATH.
BTW, I had installed in the system, 
which jq
/usr/bin/jq

but I had the same ENOENT crash when it was not found in node_modules/node-jq/bin/jq.
My workaround was to pass the '/usr/bin/jq' into 'run' method as the forth optional parameter, then it worked.
