### ISSUE TITLE
Error event not handled

### ISSUE THREAD

**Issue by gajus** [sanack/node-jq#157] opened 2019-02-21 17:44 UTC
```js
jq('.', JSON.stringify({foo: 'bar'}), {
  input: 'string',
  output: 'string'
})

```

```
Error: spawn /Users/gajus/Documents/dev/gajus/roarr-cli/node_modules/node-jq/bin/jq ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

```

**Comment by einsub** [comment] 2019-03-07 05:50
I had the same problem.
It seems to work well with version 1.3.1.

**Comment by darweshsinghcgi** [comment] 2019-03-17 15:41
Same issue here. Rolling back to 1.3.1 fixes the problem.

**Comment by davesnx** [comment] 2019-03-19 12:20
Hey, I'm not able to reproduce. 

I created a codesandbox and after that I tried locally and both works fine for me: https://codesandbox.io/s/13k0pq2km4?expanddevtools=1&fontsize=14&moduleview=1&previewwindow=tests&view=editor

Tried with node 10.6 and v10.15.2

Could you help me find out @einsub @darweshsinghcgi ?

**Comment by darweshsinghcgi** [comment] 2019-03-26 18:04
I'm currently unable to reproduce - it has disappeared. Will update if it shows up again. @davesnx

**Comment by davesnx** [comment] 2019-04-08 15:03
Closing meanwhile! 👍

**Closed by davesnx** 2019-04-08 15:03 UTC
